### ISSUE TITLE
The code can not run. Could you fix it? Thank you!

### ISSUE THREAD

**Issue by gascendcn** [charlielobster/MagneticFields#1]
The code can not run. Could you fix it? Thank you!

**Comment by charlielobster** [comment]
hi gascendcn, thanks for checking out the code! i will try and help you out!

**Comment by charlielobster** [comment]
gascendcn, how are you building the code (windows, mac?) and what's your target device os (ios, android)?

**Comment by gascendcn** [comment]
I am buliding the code on windows. my target device os is android.

![image](https://user-images.githubusercontent.com/57657833/185655900-6bd82691-0dc8-49f6-9777-d80d19a689dd.png)

when running, the isValid is false on the screen.  Thanks for your help.

**Comment by charlielobster** [comment]
Hey gascendcn, 

I hope all is well with you. Sorry for taking so long, I haven't forgot about you! I just built and deployed successfully using my original configuration and am unable to replicate your issue.  My laptop is the original machine I used to compile and build the application, and I haven't changed it much since then. It is still working as expected. The UI is pretty wonky...I need to work on that a bit.

Let me get a little more information from you first...

_What version of Unity Editor are you running?_ 
The version I have that builds ok at the moment is 2019.2.6f1, but I am working on upgrading it.

_What version of Visual Studio are you running?_ 
There is a C#-based component of the code-base that currently uses VS Community 2019. This piece includes includes the core kd-tree implementation. 

_What OS is your target device running?_ 
The Google Pixel 3 I am using is Android v12. 

_Did you enable developer mode on the device?_

_What is your target device's make and model?_

From what I can tell, the IsValid flag is only set to false here, on line 179 of Reading.cs: 

```
                case DeviceOrientation.FaceUp:
                    // FaceUp appears to be off by a PI rotation about some axis
                case DeviceOrientation.FaceDown:
                case DeviceOrientation.Unknown:
                default:
                    // these have issues
                    m_rawVector = rawVector;
                    m_isValid = false;
                    break;
```

Thus, it appears that the application is unable to recognize the orientation of your device, for some strange reason (probably needs a upgrade to the api call used to get orientation).

The vectors are all reading 0 for you as well, which implies maybe it doesn't have rights to read the device's magnetometer. That could also be an issue.

It's been a couple of years since I've touched this code, but I'm making this issue a priority, so I will make steady progress, but it may take a few more days before I can nail down what's going on.  

My development environment of choice, a desktop PC, is giving me grief about C drive space. On my desktop machine, I am presently working on upgrading the application to use a current version of Unity Editor (perhaps 2022). I want to create an iOS version as well, once we resolve the current issue you're having. I will be using the Google Pixel 3 device to test the upgrades on and will update you as soon as I get somewhere with that. I have an iPhone 8 for the iOS target device, once I get that far.

Regards, Erik

**Comment by gascendcn** [comment]
Could you upload the upgrade version code?  The older version code is missing some script configuration, so it can't run. Thanks a lot!

**Comment by charlielobster** [comment]
Hey gascendcn, 

How are you? Hope you are doing fine. Today I have been looking into Unity's latest AR Foundation support in anticipation of the upgrade. I visited this code: https://github.com/Unity-Technologies/arfoundation-samples. 

If you want to work on something, try to build those samples on your target device. I will use it as scaffolding around my old code.

Presently, I am trying to build and deploy it to my target device (Android 12 Google Pixel 3). It's built using a 2022.2.0a17 alpha branch - which I can't find. 

I did find a later beta, it might work. Anyway, it's the beta 2022.2.0b5. This version includes a Visual Studio 2022 Community install. Normally, I'd stay away from betas, but in this case, it's important to use the latest, because it will probably feature the best tracking available. The visualization of the mag field readings won't drift as much in space with better tracking. 

That was a big limitation when I wrote the app. Tracking was really new back in 2018/2019.

I am also going to find some UI tutorials to improve that aspect of the app.

Regards, Erik

**Comment by charlielobster** [comment]
Hey gascendcn, 
I just got https://github.com/Unity-Technologies/arfoundation-samples working on the latest 'Official' Unity Editor release v2021.3.8f1. There are a bunch of new AR Foundation samples to look into, it's very exciting! 
I am presently porting my code to this updated scaffolding.

**Comment by charlielobster** [comment]
Hey gascendcn,

How are you? I hope you're doing fine.

Today I'm going to being re-wiring the code starting from a recent fork of https://github.com/Unity-Technologies/arfoundation-samples. 

The new samples are terrific! I will butcher them and remove a lot of them right away since I am not using Face tracking or env probes. I will only keep the ones I need in my fork. 

However, there are several new features to me! Demos for all these new tools are bundled into this single samples app. There's record session behavior now, improved plane/point cloud tracking, some stuff called AR collaboration and world map!! These are not live on my device, but that could be just a config issue. Definitely check them out!

Ok, will create a new branch off this now. Regards, Erik

**Comment by charlielobster** [comment]
Hey gascendcn, I have to do some tricky moves in git to complete my plan of having everything  in the current master branch of the MagneticFields repository. To do this, I'm going to merge branches from 2 different repositories - shown here: https://stackoverflow.com/questions/38468700/how-to-merge-branches-in-2-different-repositories#:~:text=%20How%20to%20merge%20branches%20in%202%20different,copy%20of%20a%20repository%20containing%20the...%20More%20

**Comment by charlielobster** [comment]
Hey gascendcn, I have a working build for the 2020 Editor. This should probably also work for 2021. On the branch called [dev_kdtree_embedded](https://github.com/charlielobster/MagneticFields/tree/dev_kdtree_embedded), but feel free to check it out. It should work for any Android OS greater than v10. I want to get session recording working before I promote this branch back to master.

**Comment by charlielobster** [comment]
Please stay tuned a few more days. Updates coming shortly.

**Comment by charlielobster** [comment]
hey gascendcn, this is resolved in the latest [commit](https://github.com/charlielobster/MagneticFields/commit/b50c300e893f35a97dc96ce3a63f56295cc11ec8)to the [master branch](https://github.com/charlielobster/MagneticFields/tree/master). Please let me know if you still have any issues. Thank you again for your help!
